// <auto-generated />
using System;
using InventarVali.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InventarVali.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240815083333_AddedAutovehiculeToDb")]
    partial class AddedAutovehiculeToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventarVali.Models.Autovehicule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("HasITP")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("InsurenceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VinNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Autovehicule");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HasITP = true,
                            InsurenceDate = new DateTime(2024, 8, 15, 8, 33, 32, 660, DateTimeKind.Utc).AddTicks(7220),
                            LicensePlate = "B 06 CAR",
                            Type = "Duba",
                            VinNumber = "1XPWDBTX48D766660"
                        },
                        new
                        {
                            Id = 2,
                            HasITP = false,
                            InsurenceDate = new DateTime(2024, 8, 15, 8, 33, 32, 660, DateTimeKind.Utc).AddTicks(7222),
                            LicensePlate = "CL 06 PLM",
                            Type = "Audi R8",
                            VinNumber = "1XPWDBTX48D766660"
                        });
                });

            modelBuilder.Entity("InventarVali.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "test@email.com",
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            Email = "test2@email.com",
                            FirstName = "Michael",
                            LastName = "Cox"
                        },
                        new
                        {
                            Id = 3,
                            Email = "test4@email.com",
                            FirstName = "Vasile",
                            LastName = "Braconieru"
                        });
                });

            modelBuilder.Entity("InventarVali.Models.Goods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsTaken")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Goods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "",
                            IsTaken = true,
                            Name = "Masina",
                            Type = "Dacia Duster"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "",
                            IsTaken = false,
                            Name = "Masina",
                            Type = "Audi A6"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "",
                            IsTaken = true,
                            Name = "Laptop",
                            Type = "Asus Rog"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
